-- Stellar normalized storage schema.
-- Run this once in Supabase SQL Editor before deploying the normalized app.

create table if not exists public.stellar_ideas (
  id text primary key,
  title text not null,
  category text not null default '综合建议',
  author text not null default '匿名',
  anonymous boolean not null default true,
  content text not null,
  impact text not null default '',
  status text not null default '待确认',
  owner text not null default '待确认',
  management_response text not null default '',
  next_update_at text not null default '',
  merged_into_id text references public.stellar_ideas(id) on delete set null,
  base_heat integer not null default 50,
  heat integer not null default 50,
  votes integer not null default 1,
  heat_factors jsonb not null default '{}'::jsonb,
  delete_code_hash text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.stellar_ideas
  add column if not exists merged_into_id text references public.stellar_ideas(id) on delete set null;

create table if not exists public.stellar_votes (
  idea_id text not null references public.stellar_ideas(id) on delete cascade,
  voter_token text not null,
  created_at timestamptz not null default now(),
  primary key (idea_id, voter_token)
);

create table if not exists public.stellar_tasks (
  id text primary key,
  name text not null,
  owner text not null default '待确认',
  status text not null default '待确认',
  priority text not null default '中',
  progress integer not null default 8,
  due text not null default '待定',
  reward text not null default '待定',
  members jsonb not null default '[]'::jsonb,
  next_step text not null default '',
  plan text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stellar_status_history (
  id bigint generated by default as identity primary key,
  idea_id text not null references public.stellar_ideas(id) on delete cascade,
  from_status text not null default '',
  to_status text not null,
  response text not null default '',
  owner text not null default '',
  actor text not null default '管理层',
  created_at timestamptz not null default now()
);

create index if not exists stellar_ideas_created_at_idx on public.stellar_ideas(created_at desc);
create index if not exists stellar_ideas_merged_into_idx on public.stellar_ideas(merged_into_id);
create index if not exists stellar_history_idea_idx on public.stellar_status_history(idea_id, created_at);

create or replace function public.stellar_cast_vote(p_idea_id text, p_voter_token text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_count integer;
begin
  insert into public.stellar_votes(idea_id, voter_token)
  values (p_idea_id, p_voter_token)
  on conflict do nothing;

  get diagnostics inserted_count = row_count;
  if inserted_count = 1 then
    update public.stellar_ideas
    set votes = votes + 1, updated_at = now()
    where id = p_idea_id;
    return true;
  end if;
  return false;
end;
$$;

alter table public.stellar_ideas enable row level security;
alter table public.stellar_votes enable row level security;
alter table public.stellar_tasks enable row level security;
alter table public.stellar_status_history enable row level security;

revoke all on table public.stellar_ideas from anon, authenticated;
revoke all on table public.stellar_votes from anon, authenticated;
revoke all on table public.stellar_tasks from anon, authenticated;
revoke all on table public.stellar_status_history from anon, authenticated;
grant all on table public.stellar_ideas to service_role;
grant all on table public.stellar_votes to service_role;
grant all on table public.stellar_tasks to service_role;
grant all on table public.stellar_status_history to service_role;
grant usage, select on sequence public.stellar_status_history_id_seq to service_role;
revoke all on function public.stellar_cast_vote(text, text) from public, anon, authenticated;
grant execute on function public.stellar_cast_vote(text, text) to service_role;

-- Make newly added columns immediately visible to the REST API.
notify pgrst, 'reload schema';
